version: '2'
services:
    nav_utility-app:
        image: nav_utility
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://nav_utility-mysql:3306/nav_utility?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nav_utility-mysql:
        extends:
            file: mysql.yml
            service: nav_utility-mysql
